import { Inter, Inria_Serif, Inria_Sans } from "next/font/google";
import "./globals.css";
import ActiveSegment from "./components/ActiveSegment";

const inter = Inter({ subsets: ["latin"] });
const inria_serif = Inria_Serif({ subsets: ["latin"], weight: '400' });

// Inria Serif

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white ${inria_serif.className}`}>
        <ActiveSegment>
          {children}
        </ActiveSegment>
      </body>
    </html>
  );
}
